### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by ram1505** [mschm/node-red-contrib-homekit#10]
Hi,
I'm getting the following error when I click deploy in node-red. I defined a specific port 5555 in the config of the node.

`9 Nov 19:18:51 - [red] Uncaught Exception:
19 Nov 19:18:51 - Error: listen EADDRINUSE :::5555
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventedHTTPServer.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Accessory.publish (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at new HAPAccessoryNode (/home/pi/.node-red/node_modules/node-red-contrib-homekit/homekit.js:44:15)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:65:31)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:275:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:132:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
`

**Comment by mschm** [comment]
Am I right that this only happens, when you do a _full_ deploy? What happens when you deploy modified nodes only?

**Comment by ram1505** [comment]
It actually worked once. During the first deploy when I added the Homekit node into the flow. After that, each time I try to deploy any modification to the same node or other nodes, entire node-red will crash and won't start until I manually edit the flows json file and remove the homekit block from it.

**Comment by mschm** [comment]
To clarify, if you change the deployment mode from _Full_ to _Modified Nodes_ (see picture), does it still crash then?

<img width="271" alt="bildschirmfoto 2016-11-27 um 23 34 27" src="https://cloud.githubusercontent.com/assets/2902690/20652466/2748faee-b4fa-11e6-99e8-408255bc3d5b.png">

**Comment by ram1505** [comment]
Hi, Sorry for late reply. NO, if I select modified nodes, it doesn't crash. Sometimes it won't deploy at all. It takes very long trying to deploy if i select modified nodes. I've experienced it a few times. I then have to open up the settings.js file to manually remove the homekit chunk and try again.

**Comment by mschm** [comment]
This should be fixed by v0.2.0 :)
