### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by khazaee** [mschm/node-red-contrib-homekit#39]
C:\Users\usr>npm install -g --unsafe -perm node-red-contrib-homekit

> mdns@2.3.3 install C:\Users\usr\AppData\Roaming\npm\node_modules\node-red-contrib-homekit\node_modules\mdns
> node-gyp rebuild

C:\Users\usr\AppData\Roaming\npm\node_modules\node-red-contrib-homekit\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\usr\AppData\Roaming\npm\node_modules\node-red-contrib-homekit\node_modules\mdns
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\usr\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--unsafe" "-perm" "node-red-contrib-homekit"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\usr\npm-debug.log
npm ERR! code 1

**Comment by mschm** [comment]
I am sorry @khazaee, I have no experience with the installation under Windows and even doubt that it works at all...

**Comment by piejanssens** [comment]
@mschm I have it wokring under Windows!
@khazaee You're errors indicate that you need to install python, make sure in the python setup you indicate to setup the environment variables for you. Check https://github.com/mschm/node-red-contrib-homekit/issues/53
