### ISSUE TITLE
After upgrading to v0.2.1 crashing every deploy

### ISSUE THREAD

**Issue by marciogranzotto** [mschm/node-red-contrib-homekit#41]
My flows were working great but after upgrading to v0.2.1, I'm getting the following crash everytime I try to deploy my changes:

```
18 Jul 03:11:07 - [red] Uncaught Exception:
18 Jul 03:11:07 - Error: dns service error: name conflict
at Error (native)
at new Advertisement (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:56:10)
at Object.create [as createAdvertisement] (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:64:10)
at Advertiser.startAdvertising (/home/pi/.node-red/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
at Accessory._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/Accessory.js:532:20)
at emitOne (events.js:96:13)
at HAPServer.emit (events.js:188:7)
at HAPServer._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
at emitOne (events.js:96:13)
at EventedHTTPServer.emit (events.js:188:7)
at EventedHTTPServer.<anonymous> (/home/pi/.node-red/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
at emitNone (events.js:86:13)
at Server.emit (events.js:185:7)
at emitListeningNT (net.js:1285:10)
at _combinedTickCallback (internal/process/next_tick.js:71:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
```

I'm on Node-RED v0.17.4 on a raspberry pi

**Comment by MikaelMBerglund** [comment]
Same problem here. Node-RED v0.17.4 on OpenSuse Tumbleweed. t crashes everytime when doing a redploy in Node red. Have to start node red again and then it works until next redeploy.

**Comment by marciogranzotto** [comment]
@mschm any work arounds that we could use? This is really annoying

**Comment by matsekberg** [comment]
Same here, running on a mac mini with machos. When redeploying and an accessory has two services I get: 
"Error: Cannot add a Service with the same UUID '00000040-0000-1000-8000-0026BB765291' and subtype '043ab3f7-5fea-4a0e-8cfd-1d60c302c5d0' as another Service in this Accessory."

**Comment by rspaargaren** [comment]
These kind of crashes I have as well but not consistant...

**Comment by marciogranzotto** [comment]
I had two services running in the same accessory (a temperature/humidity sensor). After splitting into two accessories, I didn't get this problem anymore

**Comment by BarryReid** [comment]
Can confirm I'm getting the same issue +1

**Comment by adidoes** [comment]
Same problem here.

**Comment by marciogranzotto** [comment]
I've started to have the same problem again. @adidoes comment didn't work

**Comment by bahto** [comment]
Same issue here on rpi 3, latewt node-eed version.. any updates on this?

**Comment by ageorgios** [comment]
same issue

**Comment by bahto** [comment]
1 Oct 20:51:23 - [info] Starting flows
1 Oct 20:51:23 - [info] Started flows
1 Oct 20:51:51 - [info] Stopping flows
1 Oct 20:51:51 - [info] Stopped flows
1 Oct 20:51:51 - [info] Starting flows
1 Oct 20:51:51 - [info] Started flows
1 Oct 20:51:51 - [red] Uncaught Exception:
1 Oct 20:51:51 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Accessory.js:611:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/home/pi/.node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)

**Comment by deniscubic** [comment]
Same here

6 Oct 09:17:11 - [audit] {"event":"library.get.all","type":"flow","level":98,"path":"/library/flows","ip":"92.198.52.210","timestamp":1507274231604}
6 Oct 09:17:11 - [audit] {"event":"nodes.list.get","level":98,"path":"/nodes","ip":"92.198.52.210","timestamp":1507274231677}
6 Oct 09:17:11 - [audit] {"event":"comms.open","level":98,"timestamp":1507274231721}
6 Oct 09:17:11 - [audit] {"event":"nodes.configs.get","level":98,"path":"/nodes","ip":"92.198.52.210","timestamp":1507274231985}
6 Oct 09:17:15 - [audit] {"event":"flows.get","version":"v2","level":98,"path":"/flows","ip":"92.198.52.210","timestamp":1507274235782}
6 Oct 09:17:51 - [audit] {"event":"flows.set","type":"full","version":"v2","level":98,"path":"/flows","ip":"92.198.52.210","timestamp":1507274271443}
6 Oct 09:17:51 - [debug] saved flow revision: c83211cba7d4fc5fbac9a09a964f9db6
6 Oct 09:17:51 - [info] Stopping flows
6 Oct 09:17:51 - [debug] red/nodes/flows.stop : stopping flow : global
6 Oct 09:17:51 - [debug] red/nodes/flows.stop : stopping flow : fd31e26f.38d5c
6 Oct 09:17:51 - [info] Stopped flows
6 Oct 09:17:51 - [info] Starting flows
6 Oct 09:17:51 - [debug] red/nodes/flows.start : starting flow : global
6 Oct 09:17:51 - [debug] red/nodes/flows.start : starting flow : fd31e26f.38d5c
6 Oct 09:17:51 - [info] Started flows
6 Oct 09:17:51 - [red] Uncaught Exception:
6 Oct 09:17:51 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/root/node-red/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/root/node-red/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/root/node-red/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/root/node-red/node_modules/hap-nodejs/lib/Accessory.js:611:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/root/node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)
root@raspberrypinew:~/node-red#

**Comment by lsafelix75** [comment]
Same error

29 Oct 00:05:05 - Error: dns service error: name conflict
    at new Advertisement (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/pi/.node-red/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/Accessory.js:611:20)
    at emitOne (events.js:115:13)
    at HAPServer.emit (events.js:210:7)
    at HAPServer._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:115:13)
    at EventedHTTPServer.emit (events.js:210:7)
    at EventedHTTPServer.<anonymous> (/home/pi/.node-red/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
pi@orangepilite:~/.node-red$

**Comment by ClearSkySpace** [comment]
Same here:

```Nov 28 18:30:35 raspberrypi Node-RED[2279]: 28 Nov 18:30:35 - [info] Started flows
Nov 28 18:30:36 raspberrypi Node-RED[2279]: 28 Nov 18:30:36 - [red] Uncaught Exception:
Nov 28 18:30:36 raspberrypi Node-RED[2279]: 28 Nov 18:30:36 - Error: dns service error: name conflict
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at Error (native)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at new Advertisement (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:56:10)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at Object.create [as createAdvertisement] (/home/pi/.node-red/node_modules/mdns/lib/advertisement.js:64:10)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at Advertiser.startAdvertising (/home/pi/.node-red/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at Accessory._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/Accessory.js:655:20)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at emitOne (events.js:96:13)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at HAPServer.emit (events.js:188:7)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at HAPServer._onListening (/home/pi/.node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at emitOne (events.js:96:13)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at EventedHTTPServer.emit (events.js:188:7)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at EventedHTTPServer.<anonymous> (/home/pi/.node-red/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at emitNone (events.js:86:13)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at Server.emit (events.js:185:7)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at emitListeningNT (net.js:1288:10)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at _combinedTickCallback (internal/process/next_tick.js:77:11)
Nov 28 18:30:36 raspberrypi Node-RED[2279]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Nov 28 18:30:36 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 18:30:36 raspberrypi systemd[1]: nodered.service: Unit entered failed state.
Nov 28 18:30:36 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
Nov 28 18:30:36 raspberrypi systemd[1]: nodered.service: Service hold-off time over, scheduling restart.
Nov 28 18:30:36 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool..
Nov 28 18:30:36 raspberrypi systemd[1]: Started Node-RED graphical event wiring tool..
Nov 28 18:30:42 raspberrypi Node-RED[2385]: 28 Nov 18:30:42 - [info]
Nov 28 18:30:42 raspberrypi Node-RED[2385]: Welcome to Node-RED
Nov 28 18:30:42 raspberrypi Node-RED[2385]: ===================```
