### ISSUE TITLE
Error: dns service error: name conflict

### ISSUE THREAD

**Issue by deniscubic** [mschm/node-red-contrib-homekit#48]
Hm whats wrong with the **avahi-deamon** or the **node-red-contrib-homekit** node?
Can anyone help me? Reinstall/reboot did not help.

On **Deploy** with **node-red-contrib-homekit** nodes in the flow gives me this error:

```
6 Oct 14:53:51 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/root/node-red/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/root/node-red/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/root/node-red/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/root/node-red/node_modules/hap-nodejs/lib/Accessory.js:611:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._onListening (/root/node-red/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:188:7)
```

**Comment by maragelis** [comment]
You have two devices with the same name ? I am guessing here .

**Comment by deniscubic** [comment]
No i have not

**Comment by lsafelix75** [comment]
same issue here

**Comment by lsafelix75** [comment]
Is this project still going on? It seems that it is dead

**Comment by lsafelix75** [comment]
reinstall to 2.0.0 then the issue goes alway

**Comment by johnty** [comment]
a redeploy of the flow causes this error as well. it looks like the existing name is not being released when the flow is reinitialized or something...

**Comment by lsafelix75** [comment]
For those having this problem on 2.1.0. You can follow this to avoid crash when you do re-deploy.
Edit ./node-red/node_modules/node-red-contrib-homekit/homekit.js
Look for  the following lines:
   
 ```
   this.on('close', function (removed, done) {
      if (removed) {
        // This node has been deleted
        accessory.destroy()
      } else {
        // This node is being restarted
      }
      done()
    })
```
Remove the if(removed) condition to:

```
   this.on('close', function (removed, done) {
      accessory.destroy()
      done()
    })
```
I think during re-deploy, removed condition is not passed along and accessory.deploy() is never called. This ends up node names are not released and hence conflict

**Comment by johnty** [comment]
@lsafelix75, indeed, this seems to be the relevant change between 2.0.0 and 2.1.0 and should fix it. thanks!! not looking to deeply into it but a guess based on the code suggests that destroy should be called on close regardless of the 'removed' status. i don't know enough about HAP to know what the consequences are with regards to persistence etc - and perhaps there is another way to bring something offline instead of "destroy", which would allow two different cases in the close function - one called accessory.destroy() and another called "go offline" or something similar, which deregisters the dns name but keeps it in a list of devices (if i understand the purpose of persistence correctly... but without knowing how it works under the hood this is just pure conjecture).

i have since moved to using HAP-homekit by itself, without the node-red parts. maybe will look into it further next time i want to use it with node-red... :)
