### ISSUE TITLE
Error: Cannot add a Service with the same UUID

### ISSUE THREAD

**Issue by WizBangCrash** [mschm/node-red-contrib-homekit#72]
Hi,

I'm fairly new to node-red and have been experimenting with using the HomeKit node for the last few days. I've been having some anomalies and just wanted to understand if these are down to my system being configured incorrectly or known bugs.

Every time I press deploy after the first deployment of a HomeKit Switch node I get an error similar to the one below. I have re-initialised my node-red installation and deleted the items from the iOS HomeKit app a number of times, but always get the issue occurring.

Although I get the error the deployed node works from the HomeKit app on my iPhone and I get messages output each time I press the switch on the phone.

I am unable to set the status of the switch though. If I send a `{"On": false}` message to the Switch when it is showing as "On" in the iOS HomeKit app, the switch does not turn "Off" i.e. I cannot control the switch from node-red I can only respond to the messages it outputs.

Is this normal or have I configured something incorrectly.

```
6 Feb 09:36:35 - [info] Starting modified flows
6 Feb 09:36:35 - [error] [homekit-service:600efa19.32fdfc] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' and subtype 'eef16d6c-c452-4a61-996c-77af6480629d' as another Service in this Accessory.
    at Accessory.addService (/Users/daviddix/Dropbox/node-red-data/node_modules/hap-nodejs/lib/Accessory.js:151:15)
    at new HAPServiceNode (/Users/daviddix/Dropbox/node-red-data/node_modules/node-red-contrib-homekit/homekit.js:75:29)
    at createNode (/Users/daviddix/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/Users/daviddix/node-red/red/runtime/nodes/flows/Flow.js:89:35)
    at start (/Users/daviddix/node-red/red/runtime/nodes/flows/index.js:307:29)
    at /Users/daviddix/node-red/red/runtime/nodes/flows/index.js:144:21
    at tryCatchReject (/Users/daviddix/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/daviddix/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/daviddix/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/daviddix/node-red/node_modules/when/lib/makePromise.js:483:13)
```

**Comment by WizBangCrash** [comment]
For those interested in the above the error is caused by the service not being deleted when the "Deploy" button is clicked. In this case the `On.close` function does not delete the service so when the node is restarted the service already exists and throws an error.
I made a small change to the code to first check to see if the service is already defined and if not it will then add a new service. This has fixed the error and the side effect of messages being pushed to the switch after a redeployment being ignored.
@mschm I'm happy to submit a pull request if it helps, but the repo has outstanding pull requests, so I'm not sure if it is actively maintained.

Code change was in HomeKit.js at line 73:
```
    // add service
    var accessory = this.configNode.accessory
    // If it's a node restart then the service is already defined so try to get it first
    var service = accessory.getService(Service[this.serviceName])
    if (typeof service === "undefined") {
      service = accessory.addService(Service[this.serviceName], this.name, subtypeUUID)      
    }
```

**Comment by thelukasssheee** [comment]
Thanks @WizBangCrash ! Had exactly the same problem & works like a charm!

**Comment by ttuschak** [comment]
where can i find the HomeKit.js  File?
