### ISSUE TITLE
Can´t install

### ISSUE THREAD

**Issue by imp-djost** [mschm/node-red-contrib-homekit#73]
Hy, i can´t install the homekit plugin on my raspberry pi. This is the Error Log:

> mdns@2.3.4 install /home/pi/.node-red/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/pi/.node-red/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: Leaving directory '/home/pi/.node-red/node_modules/mdns/build'
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal...

**Comment by CroVlado** [comment]
i think im having the same issue can't understand why. this is the second type of thing that the node-gyp has caused failure on.. first for mDNS. 

23 Feb 15:10:09 - [info] Installing module: node-red-contrib-homekit, version: 0.2.1
23 Feb 15:10:39 - [warn] Installation of module node-red-contrib-homekit failed:
23 Feb 15:10:39 - [warn] ------------------------------------------
23 Feb 15:10:39 - [warn] npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v9.6.0
npm http fetch GET 200 https://registry.npmjs.org/node-red-contrib-homekit 871ms
npm http fetch GET 304 https://registry.npmjs.org/hap-nodejs 177ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-shims 226ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/curve25519-n2 423ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fast-srp-hap 444ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ip 462ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mdns 491ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-persist 546ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decimal.js 557ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ed25519 682ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 123ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 108ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/q 97ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/node-red-contrib-homekit/-/node-red-contrib-homekit-0.2.1.tgz 190ms
npm info lifecycle nan@2.3.5~preinstall: nan@2.3.5
npm info lifecycle mdns@2.3.4~preinstall: mdns@2.3.4
npm info lifecycle hap-nodejs@0.4.41~preinstall: hap-nodejs@0.4.41
npm info lifecycle node-red-contrib-homekit@0.2.1~preinstall: node-red-contrib-homekit@0.2.1
npm info linkStuff nan@2.3.5
npm info linkStuff mdns@2.3.4
npm info linkStuff hap-nodejs@0.4.41
npm info linkStuff node-red-contrib-homekit@0.2.1
npm info lifecycle nan@2.3.5~install: nan@2.3.5
npm info lifecycle mdns@2.3.4~install: mdns@2.3.4
> mdns@2.3.4 install /share/node-red/node_modules/mdns
> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.6.0 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/share/node-red/node_modules/mdns/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/9.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/9.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/9.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/share/node-red/node_modules/mdns',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/share/node-red/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
dns_sd_bindings.target.mk:150: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: Leaving directory '/share/node-red/node_modules/mdns/build'
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:125:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.50
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /share/node-red/node_modules/mdns
gyp ERR! node -v v9.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm info lifecycle mdns@2.3.4~install: Failed to exec install script
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-23T20_10_39_787Z-debug.log
23 Feb 15:10:39 - [warn] ------------------------------------------
