### ISSUE TITLE
Error: dns service error: unknown

### ISSUE THREAD

**Issue by kstaniek** [mschm/node-red-contrib-homekit#8]
Hi,

I have installed libavahi-compat-libdnssd-dev and then node and node-red-contrib-homekit.

When deploying homekit node I got the following error:

```
14 Nov 14:18:58 - [red] Uncaught Exception:
14 Nov 14:18:58 - Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/src/node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/src/node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/src/node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/usr/src/node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/src/node-red/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)

npm info node-red-docker@0.15.2 Failed to exec start script
npm ERR! Linux 4.4.30-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@0.15.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@0.15.2 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.
npm ERR! This is most likely a problem with the node-red-docker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-docker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-red-docker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log
```

Please let me know if I do something wrongly.

**Comment by mschm** [comment]
I am experiencing the same when I try running in Docker. The problem is that avahi-daemon won't start. This is my Dockerfile:

```
FROM nodered/node-red-docker

USER root
RUN apt-get update && \
    apt-get install -y \
    apt-utils \
    python \
    build-essential \
    make \
    g++ \
    libavahi-compat-libdnssd-dev \
    nano

RUN npm install node-red-contrib-homekit
```

Hopefully somebody else has an answer... :)

**Comment by kstaniek** [comment]
That's exactly my case.

**Comment by kstaniek** [comment]
When I run it manually:

```
root@465af8a3161d:/usr/src/node-red# /usr/sbin/avahi-daemon
Found user 'avahi' (UID 105) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.6.31 starting up.
dbus_bus_get_private(): Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
WARNING: Failed to contact D-Bus daemon.
avahi-daemon 0.6.31 exiting.
```

**Comment by kstaniek** [comment]
I have added:

```
[...]
RUN sed -i "s/#enable-dbus=yes/enable-dbus=no/g" /etc/avahi/avahi-daemon.conf
RUN service avahi-daemon start

RUN npm install node-red-contrib-homekit
```

to your Dockerfile and now avahi daemon works but the issue persists.

**Comment by tkothe** [comment]
Hi there.
Just wanted to add that I am after a solution for the same problem but have not yet been able to find it. As we seem to agree, the issue seems to be with avahi and/or dbus. According to https://github.com/nfarina/homebridge/issues/309#issuecomment-157990100 running docker with ``docker run --net=host`` could help. However, I am on a Mac and here [docker run --net=host behaves a bit odd](https://forums.docker.com/t/should-docker-run-net-host-work/14215). 

so the question would be: are you guys trying on Linux and does it work there with `--net=host`?

**Comment by felixbouleau** [comment]
@tkothe I ran into this problem recently as well. I followed the last advice given in https://github.com/nfarina/homebridge/issues/309 and edited the run.sh file. I replaced `dbus-daemon --system` with `service dbus restart`. It seems to have solved the problem for me.

Give it a whirl and let me know if it solved the problem for you as well!

**Comment by waj** [comment]
I'm running `avahi-daemon` on my Linux host and I found that mapping the DBus unix socket (/var/run/dbus/system_bus_socket) to the container, and running the container in privileged mode seems to solve the problem.

Of course this might not work for everyone, for example if you're on Mac, where avahi is not running in the host.

Maybe avahi can be executed on a separate container and map the unix socket the same way I did.

**Comment by ruudboon** [comment]
Tried it with --net=host but unfortunately it doesn't help. Got homebridge working in docker so it should be possible.

**Comment by piejanssens** [comment]
Has anyone resolved this issue? I want to get this to work in docker (synology) too.

**Comment by olapola85** [comment]
Im getting this, is this the same problem?

`Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-homekit@0.2.1
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/node_modules/mdns
gyp ERR! node -v v6.12.0
gyp ERR! node-gyp -v v3.4.0
gyp...`

**Comment by piejanssens** [comment]
@olapola85 https://github.com/Hackworth/VeraHomeKitBridge/issues/4

**Comment by matthub** [comment]
Based on https://github.com/nfarina/homebridge/issues/613#issuecomment-353638996 I've used following `Dockerfile` to deploy it on a Synology NAS, be aware to set the `diskstation` to your real server name - if it is not static that can be moved to an environment variable like in https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology

```
FROM nodered/node-red-docker
USER root

# e.g. install here gosu via https://github.com/tianon/gosu/blob/master/INSTALL.md
# ...
# fix non-root usage
RUN chown root:node-red /usr/local/bin/gosu && chmod +s /usr/local/bin/gosu

RUN apt-get update -y && apt-get install -y apt-utils build-essential python make g++ avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev

# please replace diskstation with your server name
RUN sed -i "s/#enable-dbus=yes/enable-dbus=yes/g" /etc/avahi/avahi-daemon.conf && sed -i "s/.*host-name.*/host-name=diskstation/" /etc/avahi/avahi-daemon.conf
RUN mkdir -p /var/run/dbus && mkdir -p /var/run/avahi-daemon
RUN chown messagebus:messagebus /var/run/dbus && chown avahi:avahi /var/run/avahi-daemon && dbus-uuidgen --ensure

USER node-red
RUN npm install node-red-contrib-homekit

COPY entrypoint.sh /usr/src/node-red
RUN gosu root chmod 755 /usr/src/node-red/entrypoint.sh
ENTRYPOINT /usr/src/node-red/entrypoint.sh
```

I've used a very simplistic `entrypoint.sh` as below:

```
#!/bin/bash
[[ -e /var/run/dbus.pid ]] && gosu root rm -f /var/run/dbus.pid
[[ -e /var/run/avahi-daemon/pid ]] && gosu root rm -f /var/run/avahi-daemon/pid
[[ -e /var/run/dbus/system_bus_socket ]] && gosu root rm -f /var/run/dbus/system_bus_socket
gosu root service dbus restart
gosu root service avahi-daemon restart
npm start -- --userDir /data
```

And I've started it with following `docker` command

```
docker run -d --net=host --name node-red -it -v /volume1/smarthome/node-red:/data mynodered
```

HTH

**Comment by RaymondMouthaan** [comment]
Hi @matthub,

I think its just awesome you posted your solution! I've tried it on my Synology NAS as well and it works perfectly. 💯 

My aim is to have it working within a node-red docker image ready for raspberry pi (arm), but with you solution this wouldn't be much of a problem. 

Thanks again 👍 .

**Comment by matthub** [comment]
I think I also saw that issue, but after a container restart they just worked without any issue for me again. I did not investigate deeper as I do not frequently change the nodes after initial setup. @RaymondMouthaan does it work for you again after the restart?

**Comment by RaymondMouthaan** [comment]
After restart all looked fine, but then again a redeploy made the container crash again....

But the good news there is a fork from @boneskull at https://flows.nodered.org/node/@boneskull/node-red-contrib-homekit which solves the issue :)

Currently, i am just playing with the home-kit node. Reading its out come in to a function node to check it's value (msg.payload.On). If it is false it should return msg.payload = 'off' and when its true it should return msg.payload = 'on'. But so far I'm not able to get it to work. 

Also working on the docker file to update the node-red base image to use the latest version and preferable the slim version because that reduces the size of the final image a lot.

**Comment by matthub** [comment]
@RaymondMouthaan great, thanks for sharing the link of the fork!

Regarding the value issue, I think that should work, for a boolean value I do it like following `return { "payload" : msg.payload.On ? "1" : "0" };`, for a temperature I do it like the following `return { "payload" : { "value" : msg.payload.CurrentTemperature }};`. Probably we should continue the debugging not in this thread but rather somewhere private ;-)

**Comment by RaymondMouthaan** [comment]
How can we go private? 😎

**Comment by roswennen** [comment]
Hi @matthub I have nodered running in a docker but am less familiar with dockerfiles (did everything through Synology GUI) can you give some,more details on how you work with a dockerfile on Synology or point me to a location or tutorial where I can find how to do,this.  Really want to get HomeKit running with nodered in Synology docker

**Comment by matthub** [comment]
hi @roswennen I'd sugged to use Gitter https://gitter.im/ to get in touch with me - to keep the general Docker discussion separate from this issue. To give already a hint regarding your Docker on Synology question: I think the best start would be to get familiar with the command line, connecting via ssh to your Synology, and there use the `docker` command.

Especially useful are the works from @RaymondMouthaan as you can directly use his Docker image from https://hub.docker.com/r/raymondmm/node-red-homekit/ with a command like `docker run -d --network host -e HOST_NAME=$HOSTNAME --name myhomekit raymondmm/node-red-homekit`

**Comment by puneet1984** [comment]
> Especially useful are the works from @RaymondMouthaan as you can directly use his Docker image from **https://hub.docker.com/r/raymondmm/node-red-homekit/** with a command like `docker run -d --network host -e HOST_NAME=$HOSTNAME --name myhomekit raymondmm/node-red-homekit`

> After restart all looked fine, but then again a redeploy made the container crash again....
> 
> But the good news there is a fork from @boneskull at **https://flows.nodered.org/node/@boneskull/node-red-contrib-homekit** which solves the issue :)
> 

Hello,
hope the thread is still followed by you guys.
I am interested in getting the homekit + Node-red + MQQT running in the synology docker but having issues with the bonjour protocol. I am able to run the same on raspberry Pi3 but it hangs a lot and have to manually restart the nodred and mqqt again and again every few hours.

Thus, i wanted to know based on the above discussion, which one of the two mentioned base images will work on docker with homekit protocol.

Also another question is what impact will it have if I install a **rpi compatible image** on the docker in synology.
