### ISSUE TITLE
undefined UUID error when adding any homekit node

### ISSUE THREAD

**Issue by ferdinandhelmer** [mschm/node-red-contrib-homekit#95]
On version 0.8.0:

the following stacktrace is fired when I deploy a homekit node:

```
Jan  4 20:58:50 raspi node-red[19319]: 4 Jan 21:58:49 - [error] [homekit-service:c024d9d3.2b6c78] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: undefined
Jan  4 20:58:50 raspi node-red[19319]:     at Bridge.Accessory._this.addBridgedAccessory (/home/helmer/.node-red/node_modules/hap-nodejs/dist/lib/Accessory.js:250:26)
Jan  4 20:58:50 raspi node-red[19319]:     at Bridge.Accessory._this.addBridgedAccessories (/home/helmer/.node-red/node_modules/hap-nodejs/dist/lib/Accessory.js:277:23)
Jan  4 20:58:50 raspi node-red[19319]:     at Object.getOrCreate (/home/helmer/.node-red/node_modules/node-red-contrib-homekit-bridged/lib/utils/AccessoryUtils.js:67:20)
Jan  4 20:58:50 raspi node-red[19319]:     at configure (/home/helmer/.node-red/node_modules/node-red-contrib-homekit-bridged/lib/HAPServiceNode.js:133:40)
Jan  4 20:58:50 raspi node-red[19319]:     at new init (/home/helmer/.node-red/node_modules/node-red-contrib-homekit-bridged/lib/HAPServiceNode.js:18:13)
Jan  4 20:58:50 raspi node-red[19319]:     at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
Jan  4 20:58:50 raspi node-red[19319]:     at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
Jan  4 20:58:50 raspi node-red[19319]:     at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
```

I added some debugging and it stuck me that the UUID is not at all undefined. it is true though that, for a reason I do not know, an existing accessory (judging from the data, the identical one) is found. 
Even stranger, if I comment the throw, is complains about accessory.on not being a function. Can it be that there is a incompatibility to the hap-nodejs dependency?

Any hint/fix would be greatly appreciated.

**Comment by IoTPlay** [comment]
Is node-red-contrib-homekit still maintained?
